<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="wheel_link" params="prefix diameter length origin_xyz origin_rpy mass ixx ixy ixz iyy iyz izz material rgba">
        <link name="${prefix}_wheel">
        
            <!-- Inertial properties -->
            <inertial>
                <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
                <mass value="${mass}"/>
                <inertia 
                    ixx="${ixx}"  
                    ixy="${ixy}"  
                    ixz="${ixz}" 
                    iyy="${iyy}" 
                    iyz="${iyz}" 
                    izz="${izz}"/>
            </inertial>
            
            <!-- Visual properties -->
            <visual>
                <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
                <geometry>
                    <cylinder radius="${diameter / 2}" length="${length}"/>
                </geometry>
                <material name="${material}">
                    <color rgba="${rgba}"/>
                </material>
            </visual>

            <!-- Collision properties (no material/color needed) -->
            <collision>
                <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
                <geometry>
                    <cylinder radius="${diameter / 2}" length="${length}"/>
                </geometry>
            </collision>

        </link>
    </xacro:macro>
</robot>

